apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/taqiyeddinedj/HA_Infra.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  
  syncPolicy:
    syncOptions:
    - CreateNamespce=true
    automated:
      selfHeal: true
      prune: false