#Not yet to be deployed
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: nextcloud-ingress
  namespace: nextcloud
  labels:
    name: nextcloud-ingress
spec:
  rules:
  - host: nextcloud01.icosnetcloud.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nextcloud
            port: 
              number: 80
  #tls:
  #- hosts:
    #- nextcloud.icosnet.dz
    #secretName: wapapp-tls-ca-key-pair
