apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: nextcloud
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_PASSWORD: YWRtaW4=
  #NEXTCLOUD_ADMIN_PASSWORD: YWRtaW4=
  #NEXTCLOUD_ADMIN_USER: YWRtaW4=