apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: nextcloud
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32718
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
